version: '3.8'
services:
  hdisplay:
    build: .
    image: hdisplay:latest
    container_name: hdisplay
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/healthz',r=>{if(r.statusCode!==200)process.exit(1);r.resume();}).on('error',()=>process.exit(1))",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
